'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'zh' | 'ar' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.map': 'Map',
    'nav.reports': 'Reports',
    'nav.about': 'About',
    'nav.getStarted': 'Get Started',
    'nav.safePath': 'SafePath Bronx',
    'nav.tagline': 'Intelligent Safety Navigation',
    'main.title': 'SafePath',
    'main.subtitle': 'Find your safest route',
    'main.origin': 'Enter starting location',
    'main.destination': 'Enter destination',
    'main.findRoutes': 'Find Safe Routes',
    'main.reportIssue': 'Report Safety Issue',
    'crime.title': 'Crime Data Layer',
    'crime.subtitle': 'Show recent safety incidents',
    'footer.poweredBy': 'Powered by NYC Open Data',
    'footer.realTime': 'Real-time safety analysis',
    'footer.lastUpdated': 'Last updated: Just now',
    'footer.live': 'Live',
    'report.title': 'Report Safety Issue',
    'report.poorLighting': 'Poor Lighting',
    'report.generalSafety': 'General Safety Concern',
    'report.suspiciousActivity': 'Suspicious Activity',
    'report.harassment': 'Harassment Incident',
    'report.other': 'Other Safety Issue',
    'report.additionalDetails': 'Additional details for',
    'report.optional': '(optional):',
    'route.safest': 'Safest Route',
    'route.balanced': 'Balanced Route',
    'route.fastest': 'Fastest Route',
    'route.openInMaps': 'Open in Google Maps',
    'route.safetyScore': 'Safety Score',
    'route.efficiency': 'Efficiency',
    'route.composite': 'Overall',
    'routes.title': 'Routes',
    'routes.safest': 'Safest',
    'routes.balanced': 'Balanced',
    'routes.fastest': 'Fastest',
    'routes.safety': 'Safety',
    'routes.speed': 'Speed',
    'routes.risks': 'Risks',
    'routes.score': 'Score',
    'routes.openInMaps': 'Open in Maps',
    'routes.analysisNote': 'Showing {count} incidents near routes (from {total} total)',
    'community.poorLighting': 'Poor Lighting',
    'community.safetyConcern': 'Safety Concern',
    'community.suspiciousActivity': 'Suspicious Activity',
    'community.harassment': 'Harassment',
    'community.otherIssue': 'Other Issue',
    'community.reported': 'Reported',
    'community.votes': 'Votes',
    'community.helpful': 'Helpful',
    'community.notHelpful': 'Not helpful',
    'community.details': 'Details',
    'community.communityReport': 'Community Report',
    'crime.riskLevel': 'Risk Level',
    'crime.date': 'Date',
    'crime.timeAgo': 'Time ago',
    'crime.today': 'Today',
    'crime.daysAgo': '{days} days ago',
    'crime.dayAgo': '1 day ago',
    'report.selectIssueType': 'Select Issue Type:',
    'report.additionalDetailsLabel': 'Additional Details (Optional):',
    'report.charactersRemaining': '{count}/200 characters',
    'report.cancel': 'Cancel',
    'report.submitReport': 'Submit Report',
    'report.howToReport': 'How to Report',
    'report.instructions': 'Select the type of safety issue you want to report. You can add optional details to help other users. Reports are anonymous and help build a safer community map.',
    'report.locationLabel': 'Location: {lat}, {lng}',
    'report.clickToSetLocation': 'Click anywhere on the map to set location',
    'error.enterBothLocations': 'Please enter both starting location and destination',
    'error.noRoutesFound': 'Could not find routes between these locations.',
    'error.reportSubmissionFailed': 'Error submitting report. A similar report may already exist nearby.',
    'error.mapLoadFailed': 'Failed to load map',
    'error.loadingMap': 'Loading SafePath...',
    'lang.english': 'English',
    'lang.spanish': 'Español',
    'lang.french': 'Français',
    'lang.chinese': '中文',
    'lang.arabic': 'العربية',
    'lang.russian': 'Русский',
    'reports.description': 'Learn about the data sources and reporting features that help keep our community safe.',
    'reports.crimeData': 'Crime Data Analytics',
    'reports.crimeDataDesc': 'Real-time crime statistics from NYC Open Data',
    'reports.totalCrimes': 'Current Period',
    'reports.dataSource': 'Data Source',
    'reports.communityReports': 'Community Reports',
    'reports.communityDesc': 'User-generated safety observations and alerts',
    'reports.rightClick': 'Right-click on map',
    'reports.reportTypes': 'Report Types',
    'reports.types': 'types',
    'reports.howItWorks': 'How It Works',
    'reports.step1': 'Explore',
    'reports.step1Desc': 'View real-time crime data and community reports on the interactive map',
    'reports.step2': 'Navigate',
    'reports.step2Desc': 'Get optimized safe routes with crime data analysis and risk assessment',
    'reports.step3': 'Contribute',
    'reports.step3Desc': 'Report safety issues to help build a safer community for everyone',
    'about.description': 'SafePath Bronx is a community-driven safety navigation platform designed to help residents find the safest walking routes.',
    'about.mission': 'Our Mission',
    'about.missionDesc': 'To empower communities with data-driven safety tools that help people navigate their neighborhoods with confidence and contribute to collective safety awareness.',
    'about.safety': 'Data-Driven Safety',
    'about.safetyDesc': 'Real-time crime analytics and risk assessment',
    'about.community': 'Community-Powered',
    'about.communityDesc': 'Crowdsourced reports and collaborative safety mapping',
    'about.features': 'Key Features',
    'about.feature1': 'Real-time crime data integration',
    'about.feature2': 'Smart route optimization for safety',
    'about.feature3': 'Community safety reporting system',
    'about.feature4': 'Multi-language accessibility support',
    'about.contact': 'Get Involved',
    'about.email': 'Contact',
    'about.data': 'Data Sources',
    'about.support': 'Support',
    'about.supportDesc': '24/7 community assistance'
  },
  es: {
    'nav.map': 'Mapa',
    'nav.reports': 'Reportes',
    'nav.about': 'Acerca de',
    'nav.getStarted': 'Comenzar',
    'nav.safePath': 'SafePath Bronx',
    'nav.tagline': 'Navegación Inteligente de Seguridad',
    'main.title': 'SafePath',
    'main.subtitle': 'Encuentra tu ruta más segura',
    'main.origin': 'Ingresa ubicación de inicio',
    'main.destination': 'Ingresa destino',
    'main.findRoutes': 'Encontrar Rutas Seguras',
    'main.reportIssue': 'Reportar Problema de Seguridad',
    'crime.title': 'Capa de Datos de Crimen',
    'crime.subtitle': 'Mostrar incidentes de seguridad recientes',
    'footer.poweredBy': 'Impulsado por NYC Open Data',
    'footer.realTime': 'Análisis de seguridad en tiempo real',
    'footer.lastUpdated': 'Última actualización: Ahora mismo',
    'footer.live': 'En vivo',
    'report.title': 'Reportar Problema de Seguridad',
    'report.poorLighting': 'Iluminación Deficiente',
    'report.generalSafety': 'Preocupación General de Seguridad',
    'report.suspiciousActivity': 'Actividad Sospechosa',
    'report.harassment': 'Incidente de Acoso',
    'report.other': 'Otro Problema de Seguridad',
    'report.additionalDetails': 'Detalles adicionales para',
    'report.optional': '(opcional):',
    'route.safest': 'Ruta Más Segura',
    'route.balanced': 'Ruta Balanceada',
    'route.fastest': 'Ruta Más Rápida',
    'route.openInMaps': 'Abrir en Google Maps',
    'route.safetyScore': 'Puntuación de Seguridad',
    'route.efficiency': 'Eficiencia',
    'route.composite': 'General',
    'routes.title': 'Rutas',
    'routes.safest': 'Más Segura',
    'routes.balanced': 'Balanceada',
    'routes.fastest': 'Más Rápida',
    'routes.safety': 'Seguridad',
    'routes.speed': 'Velocidad',
    'routes.risks': 'Riesgos',
    'routes.score': 'Puntuación',
    'routes.openInMaps': 'Abrir en Maps',
    'routes.analysisNote': 'Mostrando {count} incidentes cerca de rutas (de {total} total)',
    'community.poorLighting': 'Iluminación Deficiente',
    'community.safetyConcern': 'Preocupación General de Seguridad',
    'community.suspiciousActivity': 'Actividad Sospechosa',
    'community.harassment': 'Incidente de Acoso',
    'community.otherIssue': 'Otro Problema de Seguridad',
    'community.reported': 'Reportado',
    'community.votes': 'Votos',
    'community.helpful': 'Útil',
    'community.notHelpful': 'No útil',
    'community.details': 'Detalles',
    'community.communityReport': 'Reporte de Comunidad',
    'crime.riskLevel': 'Nivel de Riesgo',
    'crime.date': 'Fecha',
    'crime.timeAgo': 'Hace tiempo',
    'crime.today': 'Hoy',
    'crime.daysAgo': '{days} días atrás',
    'crime.dayAgo': 'Hace 1 día',
    'report.selectIssueType': 'Seleccionar Tipo de Problema:',
    'report.additionalDetailsLabel': 'Detalles Adicionales (Opcional):',
    'report.charactersRemaining': '{count}/200 caracteres',
    'report.cancel': 'Cancelar',
    'report.submitReport': 'Enviar Reporte',
    'report.howToReport': 'Cómo Reportar',
    'report.instructions': 'Selecciona el tipo de problema de seguridad que quieres reportar. Puedes agregar detalles opcionales para ayudar a otros usuarios. Los informes son anónimos y ayudan a construir un mapa de comunidad más seguro.',
    'report.locationLabel': 'Ubicación: {lat}, {lng}',
    'report.clickToSetLocation': 'Haz clic en cualquier lugar del mapa para establecer la ubicación',
    'error.enterBothLocations': 'Por favor, ingrese ambas ubicaciones de inicio y destino',
    'error.noRoutesFound': 'No se encontraron rutas entre estas ubicaciones.',
    'error.reportSubmissionFailed': 'Error al enviar el informe. Ya existe un informe similar cerca.',
    'error.mapLoadFailed': 'Error al cargar el mapa',
    'error.loadingMap': 'Cargando SafePath...',
    'lang.english': 'English',
    'lang.spanish': 'Español',
    'lang.french': 'Français',
    'lang.chinese': '中文',
    'lang.arabic': 'العربية',
    'lang.russian': 'Русский',
  },
  fr: {
    'nav.map': 'Carte',
    'nav.reports': 'Rapports',
    'nav.about': 'À propos',
    'nav.getStarted': 'Commencer',
    'nav.safePath': 'SafePath Bronx',
    'nav.tagline': 'Navigation Intelligente de Sécurité',
    'main.title': 'SafePath',
    'main.subtitle': 'Trouvez votre itinéraire le plus sûr',
    'main.origin': 'Entrez le lieu de départ',
    'main.destination': 'Entrez la destination',
    'main.findRoutes': 'Trouver des Itinéraires Sûrs',
    'main.reportIssue': 'Signaler un Problème de Sécurité',
    'crime.title': 'Couche de Données Criminelles',
    'crime.subtitle': 'Afficher les incidents de sécurité récents',
    'footer.poweredBy': 'Alimenté par NYC Open Data',
    'footer.realTime': 'Analyse de sécurité en temps réel',
    'footer.lastUpdated': 'Dernière mise à jour: À l\'instant',
    'footer.live': 'En direct',
    'report.title': 'Signaler un Problème de Sécurité',
    'report.poorLighting': 'Éclairage Défaillant',
    'report.generalSafety': 'Préoccupation Générale de Sécurité',
    'report.suspiciousActivity': 'Activité Suspecte',
    'report.harassment': 'Incident de Harcèlement',
    'report.other': 'Autre Problème de Sécurité',
    'report.additionalDetails': 'Détails supplémentaires pour',
    'report.optional': '(optionnel):',
    'route.safest': 'Itinéraire le Plus Sûr',
    'route.balanced': 'Itinéraire Équilibré',
    'route.fastest': 'Itinéraire le Plus Rapide',
    'route.openInMaps': 'Ouvrir dans Google Maps',
    'route.safetyScore': 'Score de Sécurité',
    'route.efficiency': 'Efficacité',
    'route.composite': 'Global',
    'routes.title': 'Itinéraires',
    'routes.safest': 'Plus Sûr',
    'routes.balanced': 'Équilibré',
    'routes.fastest': 'Plus Rapide',
    'routes.safety': 'Sécurité',
    'routes.speed': 'Vitesse',
    'routes.risks': 'Risques',
    'routes.score': 'Score',
    'routes.openInMaps': 'Ouvrir dans Maps',
    'routes.analysisNote': 'Affichage de {count} incidents près des itinéraires (sur {total} total)',
    'community.poorLighting': 'Éclairage Défaillant',
    'community.safetyConcern': 'Préoccupation Générale de Sécurité',
    'community.suspiciousActivity': 'Activité Suspecte',
    'community.harassment': 'Incident de Harcèlement',
    'community.otherIssue': 'Autre Problème de Sécurité',
    'community.reported': 'Signalé',
    'community.votes': 'Votes',
    'community.helpful': 'Utile',
    'community.notHelpful': 'Pas utile',
    'community.details': 'Détails',
    'community.communityReport': 'Rapport de Communauté',
    'crime.riskLevel': 'Niveau de Risque',
    'crime.date': 'Date',
    'crime.timeAgo': 'Il y a du temps',
    'crime.today': 'Aujourd\'hui',
    'crime.daysAgo': '{days} jours plus tôt',
    'crime.dayAgo': 'Il y a 1 jour',
    'report.selectIssueType': 'Sélectionner le Type de Problème:',
    'report.additionalDetailsLabel': 'Détails Supplémentaires (Optionnel):',
    'report.charactersRemaining': '{count}/200 caractères',
    'report.cancel': 'Annuler',
    'report.submitReport': 'Soumettre le Rapport',
    'report.howToReport': 'Comment Signaler',
    'report.instructions': 'Sélectionnez le type de problème de sécurité que vous souhaitez signaler. Vous pouvez ajouter des détails supplémentaires pour aider les autres utilisateurs. Les rapports sont anonymes et aident à construire une carte communautaire plus sûre.',
    'report.locationLabel': 'Emplacement: {lat}, {lng}',
    'report.clickToSetLocation': 'Cliquez n\'importe où sur la carte pour définir l\'emplacement',
    'error.enterBothLocations': 'Veuillez entrer les deux emplacements de départ et d\'arrivée',
    'error.noRoutesFound': 'Impossible de trouver des itinéraires entre ces emplacements.',
    'error.reportSubmissionFailed': 'Erreur lors de la soumission du rapport. Un rapport similaire pourrait déjà exister à proximité.',
    'error.mapLoadFailed': 'Échec du chargement de la carte',
    'error.loadingMap': 'Chargement de SafePath...',
    'lang.english': 'English',
    'lang.spanish': 'Español',
    'lang.french': 'Français',
    'lang.chinese': '中文',
    'lang.arabic': 'العربية',
    'lang.russian': 'Русский',
  },
  zh: {
    'nav.map': '地图',
    'nav.reports': '报告',
    'nav.about': '关于',
    'nav.getStarted': '开始使用',
    'nav.safePath': 'SafePath 布朗克斯',
    'nav.tagline': '智能安全导航',
    'main.title': 'SafePath',
    'main.subtitle': '找到您最安全的路线',
    'main.origin': '输入起始位置',
    'main.destination': '输入目的地',
    'main.findRoutes': '查找安全路线',
    'main.reportIssue': '报告安全问题',
    'crime.title': '犯罪数据层',
    'crime.subtitle': '显示最近的安全事件',
    'footer.poweredBy': '由纽约市开放数据提供支持',
    'footer.realTime': '实时安全分析',
    'footer.lastUpdated': '最后更新：刚刚',
    'footer.live': '实时',
    'report.title': '报告安全问题',
    'report.poorLighting': '照明不足',
    'report.generalSafety': '一般安全问题',
    'report.suspiciousActivity': '可疑活动',
    'report.harassment': '骚扰事件',
    'report.other': '其他安全问题',
    'report.additionalDetails': '额外详情',
    'report.optional': '（可选）：',
    'route.safest': '最安全路线',
    'route.balanced': '平衡路线',
    'route.fastest': '最快路线',
    'route.openInMaps': '在谷歌地图中打开',
    'route.safetyScore': '安全评分',
    'route.efficiency': '效率',
    'route.composite': '综合',
    'routes.title': '路线',
    'routes.safest': '最安全',
    'routes.balanced': '平衡',
    'routes.fastest': '最快',
    'routes.safety': '安全',
    'routes.speed': '速度',
    'routes.risks': '风险',
    'routes.score': '评分',
    'routes.openInMaps': '在地图中打开',
    'routes.analysisNote': '显示靠近路线（共 {total} 个）的 {count} 个事件',
    'community.poorLighting': '照明不足',
    'community.safetyConcern': '安全问题',
    'community.suspiciousActivity': '可疑活动',
    'community.harassment': '骚扰事件',
    'community.otherIssue': '其他问题',
    'community.reported': '已报告',
    'community.votes': '投票',
    'community.helpful': '有用',
    'community.notHelpful': '无用',
    'community.details': '详情',
    'community.communityReport': '社区报告',
    'crime.riskLevel': '风险等级',
    'crime.date': '日期',
    'crime.timeAgo': '时间前',
    'crime.today': '今天',
    'crime.daysAgo': '{days}天前',
    'crime.dayAgo': '1天前',
    'report.selectIssueType': '选择问题类型：',
    'report.additionalDetailsLabel': '额外详情（可选）：',
    'report.charactersRemaining': '{count}/200字符',
    'report.cancel': '取消',
    'report.submitReport': '提交报告',
    'report.howToReport': '如何报告',
    'report.instructions': '选择您要报告的安全问题类型。您可以添加可选的详细信息以帮助其他用户。报告是匿名的，并有助于构建更安全的社区地图。',
    'report.locationLabel': '位置：{lat}, {lng}',
    'report.clickToSetLocation': '点击地图上的任何位置以设置位置',
    'error.enterBothLocations': '请输入起始位置和目的地',
    'error.noRoutesFound': '无法找到这两点之间的路线',
    'error.reportSubmissionFailed': '提交报告时出错。附近可能已经存在类似的报告',
    'error.mapLoadFailed': '加载地图失败',
    'error.loadingMap': '加载SafePath...',
    'lang.english': 'English',
    'lang.spanish': 'Español',
    'lang.french': 'Français',
    'lang.chinese': '中文',
    'lang.arabic': 'العربية',
    'lang.russian': 'Русский',
  },
  ar: {
    'nav.map': 'خريطة',
    'nav.reports': 'تقارير',
    'nav.about': 'حول',
    'nav.getStarted': 'ابدأ',
    'nav.safePath': 'SafePath برونكس',
    'nav.tagline': 'ملاحة ذكية للسلامة',
    'main.title': 'SafePath',
    'main.subtitle': 'ابحث عن أكثر طريق آمن',
    'main.origin': 'أدخل موقع البداية',
    'main.destination': 'أدخل الوجهة',
    'main.findRoutes': 'العثور على طرق آمنة',
    'main.reportIssue': 'الإبلاغ عن مشكلة أمان',
    'crime.title': 'طبقة بيانات الجريمة',
    'crime.subtitle': 'إظهار حوادث الأمان الأخيرة',
    'footer.poweredBy': 'مدعوم من بيانات نيويورك المفتوحة',
    'footer.realTime': 'تحليل الأمان في الوقت الفعلي',
    'footer.lastUpdated': 'آخر تحديث: الآن',
    'footer.live': 'مباشر',
    'report.title': 'الإبلاغ عن مشكلة أمان',
    'report.poorLighting': 'إضاءة ضعيفة',
    'report.generalSafety': 'قلق أمان عام',
    'report.suspiciousActivity': 'نشاط مشبوه',
    'report.harassment': 'حادثة مضايقة',
    'report.other': 'مشكلة أمان أخرى',
    'report.additionalDetails': 'تفاصيل إضافية لـ',
    'report.optional': '(اختياري):',
    'route.safest': 'الطريق الأكثر أمانًا',
    'route.balanced': 'طريق متوازن',
    'route.fastest': 'الطريق الأسرع',
    'route.openInMaps': 'فتح في خرائط جوجل',
    'route.safetyScore': 'نقاط الأمان',
    'route.efficiency': 'الكفاءة',
    'route.composite': 'الإجمالي',
    'routes.title': 'الطرق',
    'routes.safest': 'أكثر أمانًا',
    'routes.balanced': 'متوازن',
    'routes.fastest': 'أسرع',
    'routes.safety': 'أمان',
    'routes.speed': 'سرعة',
    'routes.risks': 'المخاطر',
    'routes.score': 'الدرجة',
    'routes.openInMaps': 'فتح في خرائط جوجل',
    'routes.analysisNote': 'إظهار {count} حادث أمان بالقرب من الطرق (من {total} إجمالي)',
    'community.poorLighting': 'إضاءة ضعيفة',
    'community.safetyConcern': 'قلق أمان عام',
    'community.suspiciousActivity': 'نشاط مشبوه',
    'community.harassment': 'حادثة مضايقة',
    'community.otherIssue': 'مشكلة أخرى',
    'community.reported': 'تم الإبلاغ عن',
    'community.votes': 'تصويت',
    'community.helpful': 'مفيد',
    'community.notHelpful': 'غير مفيد',
    'community.details': 'التفاصيل',
    'community.communityReport': 'تقرير المجتمع',
    'crime.riskLevel': 'مستوى المخاطرة',
    'crime.date': 'التاريخ',
    'crime.timeAgo': 'منذ وقت',
    'crime.today': 'اليوم',
    'crime.daysAgo': '{days} أيام منذ',
    'crime.dayAgo': 'منذ يوم',
    'report.selectIssueType': 'اختر نوع مشكلة:',
    'report.additionalDetailsLabel': 'التفاصيل الإضافية (اختيارية):',
    'report.charactersRemaining': '{count}/200 حرف',
    'report.cancel': 'إلغاء',
    'report.submitReport': 'إرسال التقرير',
    'report.howToReport': 'كيفية الإبلاغ',
    'report.instructions': 'حدد نوع مشكلة الأمان التي تريد الإبلاغ عنها. يمكنك إضافة تفاصيل إضافية اختيارية لمساعدة أعضاء المجتمع الآخرين. تقارير الإبلاغ عن المشكلات مخفية عن الآخرين وتساعد على بناء خريطة أمان مجتمعي أكثر أمانًا.',
    'report.locationLabel': 'الموقع: {lat}, {lng}',
    'report.clickToSetLocation': 'انقر على أي مكان على الخريطة لتحديد الموقع',
    'error.enterBothLocations': 'يرجى إدخال موقع البداية والوجهة',
    'error.noRoutesFound': 'لم يتم العثور على طرق بين هذه المواقع',
    'error.reportSubmissionFailed': 'فشل إرسال التقرير. قد يكون هناك تقرير مماثل بالقرب',
    'error.mapLoadFailed': 'فشل تحميل الخريطة',
    'error.loadingMap': 'جاري تحميل SafePath...',
    'lang.english': 'English',
    'lang.spanish': 'Español',
    'lang.french': 'Français',
    'lang.chinese': '中文',
    'lang.arabic': 'العربية',
    'lang.russian': 'Русский',
  },
  ru: {
    'nav.map': 'Карта',
    'nav.reports': 'Отчёты',
    'nav.about': 'О нас',
    'nav.getStarted': 'Начать',
    'nav.safePath': 'SafePath Бронкс',
    'nav.tagline': 'Интеллектуальная навигация безопасности',
    'main.title': 'SafePath',
    'main.subtitle': 'Найдите самый безопасный маршрут',
    'main.origin': 'Введите начальное местоположение',
    'main.destination': 'Введите пункт назначения',
    'main.findRoutes': 'Найти безопасные маршруты',
    'main.reportIssue': 'Сообщить о проблеме безопасности',
    'crime.title': 'Слой данных о преступлениях',
    'crime.subtitle': 'Показать недавние инциденты безопасности',
    'footer.poweredBy': 'На основе открытых данных Нью-Йорка',
    'footer.realTime': 'Анализ безопасности в реальном времени',
    'footer.lastUpdated': 'Последнее обновление: Сейчас',
    'footer.live': 'В прямом эфире',
    'report.title': 'Сообщить о проблеме безопасности',
    'report.poorLighting': 'Плохое освещение',
    'report.generalSafety': 'Общая проблема безопасности',
    'report.suspiciousActivity': 'Подозрительная активность',
    'report.harassment': 'Инцидент преследования',
    'report.other': 'Другая проблема безопасности',
    'report.additionalDetails': 'Дополнительные детали для',
    'report.optional': '(необязательно):',
    'route.safest': 'Самый безопасный маршрут',
    'route.balanced': 'Сбалансированный маршрут',
    'route.fastest': 'Самый быстрый маршрут',
    'route.openInMaps': 'Открыть в Google Maps',
    'route.safetyScore': 'Оценка безопасности',
    'route.efficiency': 'Эффективность',
    'route.composite': 'Общая',
    'routes.title': 'Маршруты',
    'routes.safest': 'Самый безопасный',
    'routes.balanced': 'Сбалансированный',
    'routes.fastest': 'Самый быстрый',
    'routes.safety': 'Безопасность',
    'routes.speed': 'Скорость',
    'routes.risks': 'Риски',
    'routes.score': 'Оценка',
    'routes.openInMaps': 'Открыть в Google Maps',
    'routes.analysisNote': 'Показать {count} инцидентов безопасности вблизи маршрутов (из {total} общего количества)',
    'community.poorLighting': 'Плохое освещение',
    'community.safetyConcern': 'Общая проблема безопасности',
    'community.suspiciousActivity': 'Подозрительная активность',
    'community.harassment': 'Инцидент преследования',
    'community.otherIssue': 'Другая проблема безопасности',
    'community.reported': 'Сообщено',
    'community.votes': 'Голоса',
    'community.helpful': 'Полезно',
    'community.notHelpful': 'Бесполезно',
    'community.details': 'Детали',
    'community.communityReport': 'Сообщение сообщества',
    'crime.riskLevel': 'Уровень риска',
    'crime.date': 'Дата',
    'crime.timeAgo': 'Назад',
    'crime.today': 'Сегодня',
    'crime.daysAgo': '{days} дней назад',
    'crime.dayAgo': 'Назад',
    'report.selectIssueType': 'Выберите тип проблемы:',
    'report.additionalDetailsLabel': 'Дополнительные детали (Необязательно):',
    'report.charactersRemaining': '{count}/200 символов',
    'report.cancel': 'Отмена',
    'report.submitReport': 'Отправить отчёт',
    'report.howToReport': 'Как сообщить',
    'report.instructions': 'Выберите тип проблемы безопасности, которую вы хотите сообщить. Вы можете добавить дополнительные неответственные детали, чтобы помочь другим пользователям. Сообщения о проблемах безопасности анонимны и помогают построить более безопасную карту сообщества.',
    'report.locationLabel': 'Расположение: {lat}, {lng}',
    'report.clickToSetLocation': 'Нажмите на любую точку на карте, чтобы установить местоположение',
    'error.enterBothLocations': 'Пожалуйста, введите оба места отправления и назначения',
    'error.noRoutesFound': 'Маршруты между этими точками не найдены',
    'error.reportSubmissionFailed': 'Ошибка при отправке отчёта. Возможно, поблизости уже есть аналогичный отчёт',
    'error.mapLoadFailed': 'Не удалось загрузить карту',
    'error.loadingMap': 'Загрузка SafePath...',
    'lang.english': 'English',
    'lang.spanish': 'Español',
    'lang.french': 'Français',
    'lang.chinese': '中文',
    'lang.arabic': 'العربية',
    'lang.russian': 'Русский',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}; 